ADD: Check for special characters in a string
patil-ashutosh/go-regex-utility pull request #12
Opened 2020-10-05 07:19 UTC by binkkatal

ADD: Check for special characters in a string.

The Method ContainsSpecialChars, uses regex to validate a string.
The regex being used is `^[a-zA-Z0-9]*$`

2020-10-05 16:47 UTC, patil-ashutosh commented
@binkkatal   Thank your for raising your pull request.

2020-10-05 16:48 UTC, patil-ashutosh commented on regex/rstring/string.go
> +	isStringAlphabetic = regexp.MustCompile(`^[a-zA-Z0-9]*$`).MatchString
@binkkatal please try to address these comments.

2020-10-05 16:49 UTC, patil-ashutosh requested changes
@binkkatal Please address comments. Feel free to ping if need any help

2020-10-06 02:48 UTC, binkkatal commented
@patil-ashutosh fixed the lint issues and squashed the commits.
ready for re review

2020-10-06 03:16 UTC, binkkatal commented
@patil-ashutosh  do i need to setup codecov token for this pr to be merged?

2020-10-06 05:19 UTC, patil-ashutosh commented
> @patil-ashutosh do i need to setup codecov token for this pr to be merged?

@binkkatal No need to setup token , I fixed CodeCov issue so no need of token.
Please refresh branch once , issue will resolve

2020-10-06 05:32 UTC, binkkatal commented
> > @patil-ashutosh do i need to setup codecov token for this pr to be merged?
> 
> @binkkatal No need to setup token , I fixed CodeCov issue so no need of token.
> Please refresh branch once , issue will resolve

@patil-ashutosh  i rebased with the latest master and the upload step breaks again.
can you have a look at it

2020-10-07 14:20 UTC, merged